" vimrc entry point
" vim: set foldmethod=marker foldlevel=0:
" -----------------
" Basic settings
source ~/.vim/vimrc-base

" Load vim-plug {{{
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !mkdir -p ~/.vim/tmp
  silent !mkdir -p ~/.vim/autoload
  silent !curl -fLo ~/.vim/autoload/plug.vim
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall
endif
call plug#begin('~/.vim/bundle')
" }}}

" Universally useful
source ~/.vim/vimrc-essential
" filetype specific (plugins, bindings)
source ~/.vim/vimrc-ft-misc

" lightweight Powerline
Plug 'itchyny/lightline.vim'
Plug 'maximbaz/lightline-ale'
let g:lightline = {}
let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
 let g:lightline.component_type = {
      \     'linter_checking': 'left',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'left',
      \ }
let g:lightline.active = { 'right': [[ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]] }

" (Better) syntax support
Plug 'sheerun/vim-polyglot'
let g:polyglot_disabled = ['latex']
let g:vim_svelte_plugin_use_typescript = 1

" Some good colorschemes {{{
Plug 'NLKNguyen/papercolor-theme'
Plug 'tomasr/molokai'
Plug 'sjl/badwolf'
Plug 'w0ng/vim-hybrid'
Plug 'jonathanfilip/vim-lucius'
Plug 'gosukiwi/vim-atom-dark'
Plug 'junegunn/seoul256.vim'
Plug 'vim-scripts/wombat256.vim'
Plug 'vim-scripts/summerfruit256.vim'
if !has("gui_running") " Terminal vim can't take all colorschemes
  let g:rehash256 = 1 " For molokai
endif
" }}}

" Finalize vim-plug
call plug#end()

if (has('nvim'))
  let $TERM='xterm-256color'
endif

if &t_Co>255
  " set bg=light
  colorscheme PaperColor
else " e.g. in TTY
  colorscheme desert
endif
